language: python

python:
  - "3.6"

sudo: required

install:
  - pip install -r requirements.txt

env:
  global:
  - CONTAINER_APP=response-app
  - CONTAINER_CRON=response-cron
  - TAG=v1.0.$TRAVIS_BUILD_NUMBER

script:
- docker build -t $CONTAINER_APP:$TAG -f Dockerfile.response .
- docker build -t $CONTAINER_CRON:$TAG -f Dockerfile.cron .

deploy:
  skip_cleanup: true
  provider: script
  script: 
    - sh ./deploy.sh $CONTAINER_APP
    - sh ./deploy.sh $CONTAINER_CRON
  on:
    all_branches: true
    # branch: master

notifications:
  slack: bymiles:u7E9pEbrU1gdYCZ297DgFeua