language: python

python:
  - "3.6"

sudo: required

install:
  - pip install -r requirements.txt

env:
  global:
  - CONTAINER_APP=response-app
  - CONTAINER_CRON=response-cron
  - TAG=v1.0.$TRAVIS_BUILD_NUMBER

script:
- sh ./deploy.sh $CONTAINER_APP Dockerfile.response
- sh ./deploy.sh $CONTAINER_CRON Dockerfile.cron

notifications:
  slack: bymiles:u7E9pEbrU1gdYCZ297DgFeua